### ISSUE TITLE
Can't access `TGTG_ACCESS_TOKEN`, `TGTG_REFRESH_TOKEN`, `TGTG_USER_ID` and `TGTG_COOKIE`. 

### ISSUE THREAD

**Issue by danielkoller** [josxha/tgtg-alerts#1]
Hi, 

thanks for this useful application. Unfortunately I can't access my `TGTG_ACCESS_TOKEN`, `TGTG_REFRESH_TOKEN`, `TGTG_USER_ID` and `TGTG_COOKIE` after a successful login. Here is the error message I get -> 

<img width="434" alt="Bildschirmfoto 2023-05-12 um 10 33 25" src="https://github.com/josxha/tgtg-alerts/assets/15102417/3be533ed-51de-4b4c-94f9-040a8a9bd5b7">

Thanks for your help.

**Comment by josxha** [comment]
Thanks for creating this issue, @danielkoller! 
I fixed this issue in https://github.com/josxha/tgtg-alerts/commit/81e3af7a307c476834e91e3d0e7cc90ee567bbe5.

Please don't forget to run 
```bash
docker pull ghcr.io/josxha/tgtg-alerts:latest
```

Sorry for the issue, I created the project just last week. 😅

**Comment by danielkoller** [comment]
Awesome. Thanks for the quick fix! :)
