### ISSUE TITLE
Got banned after two weeks of usage.

### ISSUE THREAD

**Issue by danielkoller** [josxha/tgtg-alerts#2]
Thanks for your application again. Just a heads up: After about two weeks of using the alerts I got banned. Maybe it is useful to increase the interval so it is not that obvious? 

<img width="369" alt="Bildschirmfoto 2023-05-28 um 16 04 17" src="https://github.com/josxha/tgtg-alerts/assets/15102417/7fa4754a-c232-4c38-80d3-23554b3d739f">

**Comment by josxha** [comment]
Woah I'm sorry for that. It's a bit strage that that this came that suddenly. Maybe they changed their rate limitations. 
Increasing the default interval and giving the user an option to set their own interval sounds like a good idea!

**Comment by josxha** [comment]
I increased the default interval to 60 minutes. It can be manually set by using the `INTERVAL` environment variable.
This let's users set their own amout of risk in getting banned.

Thanks for creating this issue!

**Comment by danielkoller** [comment]
Thanks for the quick fix. :)
